# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fitapp',
                'doc_host': 'https://q0j0p.github.io',
                'git_url': 'https://github.com/q0j0p/fitapp',
                'lib_path': 'fitapp'},
  'syms': { 'fitapp.collector': { 'fitapp.collector.Collector': ('collector.html#collector', 'fitapp/collector.py'),
                                  'fitapp.collector.Collector.__init__': ('collector.html#collector.__init__', 'fitapp/collector.py'),
                                  'fitapp.collector.Collector.collect_data_from_elements': ( 'collector.html#collector.collect_data_from_elements',
                                                                                             'fitapp/collector.py'),
                                  'fitapp.collector.Collector.get_elements_by_css': ( 'collector.html#collector.get_elements_by_css',
                                                                                      'fitapp/collector.py'),
                                  'fitapp.collector.Collector.get_repeating_elements': ( 'collector.html#collector.get_repeating_elements',
                                                                                         'fitapp/collector.py'),
                                  'fitapp.collector.Collector.get_url': ('collector.html#collector.get_url', 'fitapp/collector.py')},
            'fitapp.core': {'fitapp.core.foo': ('core.html#foo', 'fitapp/core.py')}}}
