# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fitapp',
                'doc_host': 'https://q0j0p.github.io',
                'git_url': 'https://github.com/q0j0p/fitapp',
                'lib_path': 'fitapp'},
  'syms': {'fitapp.core': {'fitapp.core.foo': ('core.html#foo', 'fitapp/core.py')}}}
